/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package C05_pjSeleccionDoble;

import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Torres
 */
public class frmHectareas extends javax.swing.JFrame {

    /**
     * Creates new form frmHectareas
     */
    public frmHectareas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAlgodon = new javax.swing.JTextField();
        txtMaiz = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("HECTAREAS DE ALGODON Y MAIZ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 250, 18);

        txtAlgodon.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtAlgodon.setBorder(javax.swing.BorderFactory.createTitledBorder("Semillas de Algodon"));
        getContentPane().add(txtAlgodon);
        txtAlgodon.setBounds(40, 50, 170, 60);

        txtMaiz.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtMaiz.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semillas de Maiz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtMaiz);
        txtMaiz.setBounds(230, 50, 170, 60);

        btnCalcular.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(80, 120, 130, 30);

        btnLimpiar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(220, 120, 130, 30);

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 390, 110);

        btnSalir.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(20, 280, 110, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-447)/2, (screenSize.height-369)/2, 447, 369);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //
        int algodon=Integer.parseInt(txtAlgodon.getText());
        int maiz=Integer.parseInt(txtMaiz.getText());
        
        //
        double costoAlgodon=0,costoMaiz=0;
        if (algodon+maiz>150)
            JOptionPane.showMessageDialog(null,
                  "Modifique los valores para que no exceda a 150 hectareas",
                  "Sistema de control",
                  JOptionPane.ERROR_MESSAGE);
        else{
            costoAlgodon=3*algodon;
            costoMaiz=5*maiz;
        
            //
            String masAlto;
            double costoAlto;
            if (costoAlgodon>costoMaiz){
                masAlto="Algodon";
                costoAlto=costoAlgodon;
            }else {
                masAlto="Maiz";
                costoAlto=costoMaiz;
            }
        
            //
            txtR.setText("");
            txtR.append("Hectareas de Algodon: "+algodon);
            txtR.append("\nHectareas de Maiz: "+maiz);
            txtR.append("\nTotal de Hectareas: "+(algodon+maiz));
            txtR.append("\nCosto de Algodon $: "+String.format("%.2f",costoAlgodon));
            txtR.append("\nCosto de Maiz $: "+String.format("%.2f",costoMaiz));
            txtR.append("\nEl Costo mas alto es para : "+masAlto+" con un monto de $ "+costoAlto);
        }
         
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAlgodon.setText("");
        txtMaiz.setText("");
        txtR.setText("");
        txtAlgodon.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int r=JOptionPane.showOptionDialog(this, 
            "Estas seguro de salir...?", 
            "Sistema de Ventas", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,null,null);
        if (r==0) System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHectareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHectareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHectareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHectareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHectareas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlgodon;
    private javax.swing.JTextField txtMaiz;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
