/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package C02_pjEmpresa;

/**
 *
 * @author Manuel Torres
 */
public class frmPago extends javax.swing.JFrame {

    /**
     * Creates new form frmPago
     */
    public frmPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        txtTarifa = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PAGO DE EMPLEADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 160, 14);
        

        jLabel2.setText("EMPLEADO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 80, 14);

        jLabel3.setText("HORAS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 80, 14);

        jLabel4.setText("TARIFA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 90, 60, 14);
        getContentPane().add(txtEmpleado);
        txtEmpleado.setBounds(100, 50, 303, 30);
        getContentPane().add(txtHoras);
        txtHoras.setBounds(100, 80, 60, 30);
        getContentPane().add(txtTarifa);
        txtTarifa.setBounds(340, 80, 60, 30);

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(120, 130, 90, 30);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(300, 130, 90, 30);

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 188, 380, 153);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 437) / 2, (screenSize.height - 394) / 2, 437, 394);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        //Entrada 
        int horas = Integer.parseInt(txtHoras.getText());
        double tarifa = Double.parseDouble(txtTarifa.getText());

        //Proceso
        double basico = horas * tarifa;
        double bonificacion = basico * 0.2;
        double neto = (basico + bonificacion) * 0.9;

        //Salida
        txtR.setText(" ** Resumen de Pago a Empleado ** \n");
        txtR.append("\nEl básico es: " + basico);
        txtR.append("\nLa bonificación es: " + bonificacion);
        txtR.append("\nEl neto es: " + neto);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtEmpleado.setText("");
        txtHoras.setText("");
        txtTarifa.setText("");
        txtR.setText("");
        txtEmpleado.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPago().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextArea txtR;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables
}
