package mysql_sistema.cap_06_Implementacion_Sistema_informacion.frm_consultas;// 1. importando

import mysql_sistema.cap_06_Implementacion_Sistema_informacion.conexion.conexiondb;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class frm_matenimineto extends javax.swing.JFrame {

    // 2. crear objetos  globales
    Connection cone = conexiondb.conetarbd();
    Statement st = null; // prepara consulta - SQL
    PreparedStatement pst = null;
    ResultSet rs = null; // tabla temporal

    //3. objeto modelo tabla
    DefaultTableModel dtm = new DefaultTableModel();

    void TraerCategorias() {
        try {
            st = cone.createStatement();
            rs = st.executeQuery("select * from personal");

            Object datos[] = new Object[4];
            // limpiar tabla
            int fila = dtm.getRowCount();
            if (fila > 0) {
                for (int i = 0; i < fila; i++) {
                    dtm.removeRow(0);
                }
            }

            while (rs.next()) {
                datos[0] = rs.getInt(1); // guardando el dato en el array
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                
                dtm.addRow(datos); // adicionando los datos en el modelo de la tabla

            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public frm_matenimineto() {
        initComponents();
        //4. programando en el constructor del formulario
        String titulos[] = {"Codigo", "nombres", "sueldo", "edad"};
        dtm.setColumnIdentifiers(titulos);
        tablacategoria.setModel(dtm);
        // mostrar los stados
        TraerCategorias();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        btncod = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacategoria = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE PERSONAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setText("SUELDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("CODIGO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, -1));
        getContentPane().add(txtdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, -1));

        btncod.setText("CONSULTAR");
        btncod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncodActionPerformed(evt);
            }
        });
        getContentPane().add(btncod, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        btncerrar.setText("cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btn_nuevo.setText("INSERTAR");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 90, -1));

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 100, -1));

        btn_modificar.setText("ACTUALIZAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 90, -1));

        tablacategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablacategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacategoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 490, 140));

        jLabel5.setText("edad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
    // BOTON CERRAR 
    dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
     // boton  nuevo 
        txtcod.setText("");
        txtnom.setText("");
        txtdesc.setText("");
        txt_edad.setText("");
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        try {
            st = cone.createStatement();
            // variables
            int id = Integer.parseInt(txtcod.getText());
            String sql = "delete from personal where codigo=" + id;
            
            int r = JOptionPane.showConfirmDialog(this, "estas seguro de eliminar?", "ALERTA", JOptionPane.YES_NO_OPTION);
            if(r==0){
                st.executeUpdate(sql);
                TraerCategorias();
                btn_nuevoActionPerformed(evt);
            }
            



            
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // boton  modificar
        try {
            String sql;
            sql = "update personal set nombre=?, sueldo=?, edad=? where codigo=?; ";

            pst = cone.prepareStatement(sql);
            // adicionando los parametros
            pst.setString(1, txtnom.getText());
            pst.setInt(2, Integer.parseInt(txtdesc.getText()));
            pst.setInt(3, Integer.parseInt(txt_edad.getText()));
            pst.setInt(4, Integer.parseInt(txtcod.getText()));

            int r =  JOptionPane.showConfirmDialog(this, "estas seguro de modificar?", "ALERTA", JOptionPane.YES_NO_OPTION);
            
            if (r == 0) {
                pst.executeUpdate();
                //muestra programa
                TraerCategorias();
                btn_nuevoActionPerformed(evt);

            }
            //ejecutar


        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_btn_modificarActionPerformed

    private void tablacategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacategoriaMouseClicked
        // evento click de la jtabla
        txtcod.setText("" + dtm.getValueAt(tablacategoria.getSelectedRow(), 0));
        txtnom.setText("" + dtm.getValueAt(tablacategoria.getSelectedRow(), 1));
        txtdesc.setText("" + dtm.getValueAt(tablacategoria.getSelectedRow(), 2));
        txt_edad.setText("" + dtm.getValueAt(tablacategoria.getSelectedRow(), 3));


    }//GEN-LAST:event_tablacategoriaMouseClicked

    private void btncodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncodActionPerformed
        // consultar por  codigo
        try {
            // consultar por codigo
            st = cone.createStatement();
            // variables
            int id = Integer.parseInt(JOptionPane.showInputDialog("ingrese su codigo"));
            String sql = "select * from personal where codigo=" + id;
            rs = st.executeQuery(sql);

            String [] datos = new String[4];
            //limpíar tabla

            int fila = dtm.getRowCount();
            if (fila > 0) {
                for (int i = 0; i < fila; i++) {
                    dtm.removeRow(0);
                }
            }

            //leer datos
            while (rs.next()) 
            {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                dtm.addRow(datos);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btncodActionPerformed

      void salir(){
        int r = JOptionPane.showConfirmDialog(this, "estas seguro de cerrar?", "ALERTA", JOptionPane.YES_NO_OPTION);
        if(r==0)System.exit(0);
    }
    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // BOTON GUARDAR
        try {
            String sql = "insert into personal values(?,?,?,?)";
            
            pst = cone.prepareStatement(sql);
            //adicionando datos al parametro
            pst.setInt(1, Integer.parseInt(txtcod.getText()));
            pst.setString(2, txtnom.getText());
            pst.setInt(3, Integer.parseInt(txtdesc.getText()));
            pst.setInt(4, Integer.parseInt(txt_edad.getText()));
            
            
            int r = JOptionPane.showConfirmDialog(this, "estas seguro de insertar?", "ALERTA", JOptionPane.YES_NO_OPTION);
            if(r==0){
                //ejecutar la sentencia
                pst.executeUpdate();
                System.out.println("guardado ok");
                // mostrando categorias
                TraerCategorias();
                btn_nuevoActionPerformed(evt);
            }
        

          
           

            
            
        } catch (Exception e) {
            
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_matenimineto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_matenimineto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_matenimineto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_matenimineto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_matenimineto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btncod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacategoria;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
