/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package C05_pjSeleccion;

import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Torres
 */
public class frmRenta extends javax.swing.JFrame {

    /**
     * Creates new form frmRenta
     */
    public frmRenta() {
        initComponents();
        getRootPane().setDefaultButton(btnMostrar);
        rbPequeño.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgClases = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbPequeño = new javax.swing.JRadioButton();
        rbMediano = new javax.swing.JRadioButton();
        rbGrande = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        txtDias = new javax.swing.JTextField();
        txtKm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("RENTA DE AUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 170, 20);

        bgClases.add(rbPequeño);
        rbPequeño.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbPequeño.setText("Pequeño");
        getContentPane().add(rbPequeño);
        rbPequeño.setBounds(60, 70, 100, 27);

        bgClases.add(rbMediano);
        rbMediano.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbMediano.setText("Mediano");
        getContentPane().add(rbMediano);
        rbMediano.setBounds(60, 100, 100, 27);

        bgClases.add(rbGrande);
        rbGrande.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbGrande.setText("Grande");
        getContentPane().add(rbGrande);
        rbGrande.setBounds(60, 130, 90, 27);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clase de Auto"));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 150, 130);

        btnMostrar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(30, 200, 190, 30);

        btnLimpiar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(220, 200, 190, 30);

        txtR.setColumns(20);
        txtR.setRows(5);
        txtR.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen de la Renta"));
        jScrollPane1.setViewportView(txtR);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 400, 120);

        btnSalir.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(20, 370, 120, 30);

        txtDias.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtDias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dias Alquilados:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtDias);
        txtDias.setBounds(210, 50, 210, 60);

        txtKm.setBorder(javax.swing.BorderFactory.createTitledBorder("Kilometros recorridos: "));
        getContentPane().add(txtKm);
        txtKm.setBounds(210, 120, 210, 60);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-454)/2, (screenSize.height-453)/2, 454, 453);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        //  
        int dias = Integer.parseInt(txtDias.getText());
        double km = Double.parseDouble(txtKm.getText());
        
        //
        double tarifa=0.0;
        if (rbPequeño.isSelected()) tarifa=15;
        if (rbMediano.isSelected()) tarifa=20;
        if (rbGrande.isSelected()) tarifa=30;
        
        //
        double costo=0.0;
        if (rbPequeño.isSelected()) costo=0.2*km;
        if (rbMediano.isSelected()) costo=0.3*km;
        if (rbGrande.isSelected()) costo=0.4*km;
        
        //
        double monto=(tarifa*dias)+costo;
        
        double aumento=0;
        if (km>10) aumento=monto*(25/100.0);
        
        //
        monto=monto+aumento;
        
        //
        txtR.setText("");
        txtR.append("La cantidad de dias es: "+dias);
        txtR.append("\nLa tarifa asignada es: $ "+String.format("%.2f",tarifa));
        txtR.append("\nEl costo por Km es: $ "+String.format("%.2f",costo));
        txtR.append("\nEl Monto a Pagar es: $ "+String.format("%.2f",monto));
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // 
        txtDias.setText("");
        txtKm.setText("");
        txtR.setText("");
        txtDias.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // 
        int r=JOptionPane.showOptionDialog(this, 
            "Estas seguro de salir...?", 
            "Sistema de Ventas", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,null,null);
        if (r==0) System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRenta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgClases;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbGrande;
    private javax.swing.JRadioButton rbMediano;
    private javax.swing.JRadioButton rbPequeño;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
